# CircleCI build configuration
# Based on: https://circleci.com/docs/2.0/language-go/#sample-configuration

version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11
    working_directory: /home/circleci/goevernote

    steps:
      - checkout

      - run:
          name: Print versions
          command: |
            set -x
            go version
            go env

      - run:
          name: Ensure go modules are up to date
          command: |
            go mod tidy -v
            git diff --name-only --exit-code

      - run:
          name: Install Go packages
          command: go install -v ./...
