// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package notestore

import (
	"bytes"
	"fmt"

	"git.apache.org/thrift.git/lib/go/thrift"

	"github.com/rastech/goevernote/errors"
	"github.com/rastech/goevernote/limits"
	"github.com/rastech/goevernote/types"
	"github.com/rastech/goevernote/userstore"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = userstore.GoUnusedProtection__
var _ = types.GoUnusedProtection__
var _ = errors.GoUnusedProtection__
var _ = limits.GoUnusedProtection__

func init() {
}
